# Build and publish Docker images for multible architectures.
# 
# Pushing an image to codeberg as container registry,
# package owner will be the repo owner.
#
# this config also shows usage of yaml aliases and
# was taken from https://codeberg.org/6543/docker-images/src/commit/37e29c227717c1c07d2776cddcf14725bf952875/.woodpecker/hello.yml

when:
  branch: main

variables:
  - &file Dockerfile
  - &repo git.jmbit.de/${CI_REPO_OWNER}/${CI_REPO_NAME}

steps:
  dryrun:
    image: git.jmbit.de/jmb/docker-hugo
    commands:
      - hugo --minify
    when:
      event: [ pull-request, push]

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
      repo: *repo
      registry: git.jmbit.de
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: forgejo_token
    when:
      event: push

